name: deep
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.1
  - matplotlib
  - networkx
  - numpy
  - openai
  - pandas
  - pytest
  - regex
  - scikit-learn
  - scipy
  - tensorboard
  - tqdm
  - gdown
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - datasets
  - pytorch_geometric
  - fsspec
  - einops
  - tiktoken
  - pybars3
  - sfe1ed40::torcheval
